enum Flags {
  DISCORD_EMPLOYEE = 1,
  DISCORD_PARTNER = 2,
  HYPESQUAD_EVENTS = 4,
  BUG_HUNTER_LEVEL_ONE = 8,
  HYPESQUAD_BRAVERY = 64,
  HYPESQUAD_BRILLIANCE = 128,
  HYPESQUAD_BALANCE = 256,
  EARLY_SUPPORTER = 512,
  TEAM_USER = 1024,
  SYSTEM = 4096,
  BUG_HUNTER_LEVEL_TWO = 16384,
  VERIFIED_BOT_DEVELOPER = 131072
}

enum ActivityType {
  PLAYING = 0,
  STREAMING = 1,
  LISTENING = 2,
  WATCHING = 3,
  CUSTOM = 4
}

export { Flags, ActivityType };
